// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhbparfqqibumswhrzdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oYnBhcmZxcWlidW1zd2hyemR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODMzMDMsImV4cCI6MjA2NTQ1OTMwM30.MhdQ1EdMCZ1EpYe9JmHQtSuIvmaLjf9dOUP3eExmlZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);